### ISSUE TITLE
Payload size field in all inner headers for tunneling protocols do not take into account inner FCS

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/ixia-c#112]
Issue can be reproduced using https://github.com/open-traffic-generator/conformance/blob/dev-vxlan-vib/features/flows/headers/vxlan/test_vxlan_header_with_inner_ipv6_traffic.py

The issue is, in this particular test, we're configuring following headers:
```
f1.packet.ethernet().ipv4().udp().vxlan().ethernet().ipv6().tcp()
```

The expected payload size as shown in IPv6 Header's (inner) field should be:
```
256B -14B (outer ethernet) -4B (outer FCS) -20B (outer IPv4) -8B (outer UDP) -8B (VxLAN) -14B (inner ethernet) -40B (inner IPv6) -4B (inner FCS) = 144B
```
But packet captured in ixia-c's rx port shows 148B. In comparison, IxNetwork ports show 144B only.

The issue is, the payload size calculation for inner headers do not take into account the inner FCS size. Hence the bug might also be there in other headers that are configured as inner headers.

**Comment by biplamal** [comment]
Resolved in v0.0.1-3722
