### ISSUE TITLE
[urgent][security] Remove TLS 1.0 and TLS1.1 from ixia-c controller

### ISSUE THREAD

**Issue by chrispsommers** [open-traffic-generator/ixia-c#125]
A customer is mandating we disable/remove TLS 1.0 and TLS1.1 from the controller as these are considered security risks. ixia-c is being used in a CI/CD pipeline and the customer treats this the same as a production environment (from the standpoint of security) and is threatening to halt usage. If for some reason we need these to be available, I suggest we disable them by default and add command-line options to enable them, but they should probably be removed.

**Comment by ankur-sheth** [comment]
@biplamal can you please mark this as resolved now that we have an Ixia-c release that fixes it?

**Comment by biplamal** [comment]
Fixed in https://github.com/open-traffic-generator/ixia-c/releases/tag/v0.0.1-4064
