### ISSUE TITLE
Generating 100Gbps to prove Dual 100Gbps COnnectx5 and E810 CQDA2

### ISSUE THREAD

**Issue by jimthedj65** [open-traffic-generator/ixia-c#129]
@ashutshkumr Hi Ashutskumr,

We have 2 systems with 3 x E810-CQDA2 3 x Connects 5 CDAT dual-port 100 Gbps cards. We want to drive traffic to finish a report on proving independently 1.2Tbps ipsec. Is it possible to obtain a short-term license for 90 days to obtain the PMD driver to drive 100Gbps.

Once were over this tight budget phase we will be gearing up for scaling the solution for AI and Telecom workloads.?

I would like also to access your slack space?

Thanks in advance for any assistance.

**Comment by jimthedj65** [comment]
no longer required

**Comment by arkajyoti-cloud** [comment]
Closing this case
