### ISSUE TITLE
TE-3.7: OTG pushconfig is failing 

### ISSUE THREAD

**Issue by bkreddy143** [open-traffic-generator/ixia-c#138]
script : github.com/openconfig/featureprofiles/feature/gribi/otg_tests/base_hierarchical_nhg_update

base_hierarchical_nhg_update_test.go:149: PushConfig(t) on ATE{Dims:Dims{Name:127.0.0.1:40051 Vendor:IXIA HardwareModel: SoftwareVersion: Ports:map[port1:Port{Name:135.227.241.22;10;1 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port2:Port{Name:135.227.241.22;10;2 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED} port3:Port{Name:135.227.241.22;10;3 Speed:SPEED_UNSPECIFIED CardModel: PMD:PMD_UNSPECIFIED}] CustomData:map[]}}: {
          "code": 3,
          "errors": [
            "error on request {\nconfig: {\n  ports: {\n    location: \"135.227.241.22;10;1\"\n    name: \"port1\"\n  }\n  ports: {\n    location: \"135.227.241.22;10;2\"\n    name: \"port2\"\n  }\n  ports: {\n    location: \"135.227.241.22;10;3\"\n    name: \"port3\"\n  }\n  devices: {\n    ethernets: {\n      connection: {\n        choice: port_name\n        port_name: \"port1\"\n      }\n      ipv4_addresses: {\n        gateway: \"192.0.2.1\"\n        address: \"192.0.2.2\"\n        prefix: 30\n        name: \"atePort1.IPv4\"\n      }\n      mac: \"02:00:01:01:01:01\"\n      mtu: 1500\n      name: \"atePort1.Eth\"\n    }\n    name: \"atePort1\"\n  }\n  devices: {\n    ethernets: {\n      connection: {\n        choice: port_name\n        port_name: \"port2\"\n      }\n      ipv4_addresses: {\n        gateway: \"192.0.2.5\"\n        address: \"192.0.2.6\"\n        prefix: 30\n        name: \"atePort2.IPv4\"\n      }\n      mac: \"02:00:02:01:01:01\"\n      mtu: 1500\n      name: \"atePort2.Eth\"\n    }\n    name: \"atePort2\"\n  }\n  devices: {\n    ethernets: {\n      connection: {\n        choice: port_name\n        port_name: \"port3\"\n      }\n      ipv4_addresses: {\n        gateway: \"192.0.2.9\"\n        address: \"192.0.2.10\"\n        prefix: 30\n        name: \"atePort3.IPv4\"\n      }\n      mac: \"02:00:03:01:01:01\"\n      mtu: 1500\n      name: \"atePort3.Eth\"\n    }\n    name: \"atePort3\"\n  }\n  flows: {\n    tx_rx: {\n      choice: device\n      device: {\n        mode: mesh\n        tx_names: \"atePort1.IPv4\"\n        rx_names: \"atePort2.IPv4\"\n      }\n    }\n    packet: {\n      choice: ethernet\n      ethernet: {\n        dst: {\n          choice: value\n          value: \"00:1A:11:00:1A:BC\"\n        }\n        src: {\n          choice: value\n          value: \"02:00:01:01:01:01\"\n        }\n      }\n    }\n    packet: {\n      choice: ipv4\n      ipv4: {\n        src: {\n          choice: value\n          value: \"192.0.2.2\"\n        }\n        dst: {\n          choice: value\n          value: \"198.51.100.0\"\n        }\n      }\n    }\n    packet: {\n      choice: ipv4\n      ipv4: {\n        src: {\n          choice: increment\n          increment: {\n            start: \"198.18.0.0\"\n            step: \"0.0.0.1\"\n            count: 65000\n          }\n        }\n        dst: {\n          choice: increment\n          increment: {\n            start: \"198.19.0.0\"\n            step: \"0.0.0.1\"\n            count: 65000\n          }\n        }\n      }\n    }\n    metrics: {\n      enable: true\n      loss: false\n      timestamps: false\n    }\n    name: \"Port 1 to Port 2\"\n  }\n  flows: {\n    tx_rx: {\n      choice: device\n      device: {\n        mode: mesh\n        tx_names: \"atePort1.IPv4\"\n        rx_names: \"atePort3.IPv4\"\n      }\n    }\n    packet: {\n      choice: ethernet\n      ethernet: {\n        dst: {\n          choice: value\n          value: \"00:1A:11:00:1A:BC\"\n        }\n        src: {\n          choice: value\n          value: \"02:00:01:01:01:01\"\n        }\n      }\n    }\n    packet: {\n      choice: ipv4\n      ipv4: {\n        src: {\n          choice: value\n          value: \"192.0.2.2\"\n        }\n        dst: {\n          choice: value\n          value: \"198.51.100.0\"\n        }\n      }\n    }\n    packet: {\n      choice: ipv4\n      ipv4: {\n        src: {\n          choice: increment\n          increment: {\n            start: \"198.18.0.0\"\n            step: \"0.0.0.1\"\n            count: 65000\n          }\n        }\n        dst: {\n          choice: increment\n          increment: {\n            start: \"198.19.0.0\"\n            step: \"0.0.0.1\"\n            count: 65000\n          }\n        }\n      }\n    }\n    metrics: {\n      enable: true\n      loss: false\n      timestamps: false\n    }\n    name: \"Port 1 to Port 3\"\n  }\n  flows: {\n    tx_rx: {\n      choice: port\n      port: {\n        tx_name: \"atePort1\"\n      }\n    }\n    packet: {\n      choice: ethernet\n      ethernet: {\n        dst: {\n          choice: value\n          value: \"00:1A:11:00:1A:BC\"\n        }\n        src: {\n          choice: value\n          value: \"02:00:01:01:01:01\"\n        }\n      }\n    }\n    packet: {\n      choice: ipv4\n      ipv4: {\n        src: {\n          choice: value\n          value: \"192.0.2.2\"\n        }\n        dst: {\n          choice: value\n          value: \"198.51.100.0\"\n        }\n      }\n    }\n    packet: {\n      choice: ipv4\n      ipv4: {\n        src: {\n          choice: increment\n          increment: {\n            start: \"198.18.0.0\"\n            step: \"0.0.0.1\"\n            count: 65000\n          }\n        }\n        dst: {\n          choice: increment\n          increment: {\n            start: \"198.19.0.0\"\n            step: \"0.0.0.1\"\n            count: 65000\n          }\n        }\n      }\n    }\n    metrics: {\n      enable: true\n      loss: false\n      timestamps: false\n    }\n    name: \"Port 1 to Port 2 and Port 3\"\n  }\n}\n}: {\n  \"code\":  3,\n  \"kind\":  \"validation\",\n  \"errors\":  [\n    \"Tx port \\\"atePort1\\\" in flow \\\"Port 1 to Port 2 and Port 3\\\" is not part of the configured ports or LAGs\"\n  ]\n}"

**Comment by arkajyoti-cloud** [comment]
Provided a fix. Please run it using latest release build combination.
