### ISSUE TITLE
snappi-ixia-c.py is throwing exception.

### ISSUE THREAD

**Issue by jvadalia** [open-traffic-generator/ixia-c#53]
I have created veth1 and veth2 ports and assigned it to traffic engines.  

udo ip link add veth1 type veth peer name veth2
sudo ip link set veth1 up
sudo ip link set veth2 up

docker run -d --network=host ixiacom/ixia-c-controller --accept-eula --http-port 80 --disable-app-usage-reporter
docker run --net=host -d ixiacom/ixia-c-app-usage-reporter

docker run --net=host --privileged -d         \
  -e OPT_LISTEN_PORT="5555"                   \
  -e ARG_IFACE_LIST="virtual@af_packet,veth1"  \
  -e OPT_NO_HUGEPAGES="Yes"                   \
  ixiacom/ixia-c-traffic-engine

docker run --net=host --privileged -d         \
  -e OPT_LISTEN_PORT="5556"                   \
  -e ARG_IFACE_LIST="virtual@af_packet,veth2"  \
  -e OPT_NO_HUGEPAGES="Yes"                   \
  ixiacom/ixia-c-traffic-engine

Now running running snappi-ixia-c.py (with http://localhost:80) throws following exception:

root@user1:/opt/ixia-c/snappi-tests/scripts# python snappi-ixia-c.py 

2022-01-09 23:10:08 [snappi.snappi] [WARNING] Certificate verification is disabled
2022-01-09 18:10:08.092889 Starting connection to controller                     ... 
2022-01-09 18:10:08.096778 Starting configuration apply                          ... 
Traceback (most recent call last):
  File "snappi-ixia-c.py", line 155, in <module>
    Traffic_Test()
  File "snappi-ixia-c.py", line 86, in Traffic_Test
    api.set_config(configuration)
  File "/home/vadalia/.local/lib/python2.7/site-packages/snappi/snappi.py", line 58806, in set_config
    return_object=self.response_warning(),
  File "/home/vadalia/.local/lib/python2.7/site-packages/snappi/snappi.py", line 107, in send_recv
    headers=headers,
  File "/home/vadalia/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vadalia/.local/lib/python2.7/site-packages/requests/sessions.py", line 697, in send
    r.content
  File "/home/vadalia/.local/lib/python2.7/site-packages/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/vadalia/.local/lib/python2.7/site-packages/requests/models.py", line 761, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))

**Comment by ashutshkumr** [comment]
FYI, I've checked this against python 2.7.18 and python 3.8.10.

requests version:
```sh
python2 -m pip freeze | grep requests
requests==2.27.1

python3 -m pip freeze | grep requests
requests==2.22.0
requests-unixsocket==0.2.0
```

**Comment by jvadalia** [comment]
Still having same issue after creating virtualenv for python 
Required containers are running:
CONTAINER ID   IMAGE                               COMMAND                  CREATED        STATUS        PORTS     NAMES
7e987d30e85e   ixiacom/ixia-c-app-usage-reporter   "python -B ./run.py"     41 hours ago   Up 41 hours             gracious_faraday
1d808b5beab4   ixiacom/ixia-c-controller           "./bin/controller --…"   41 hours ago   Up 41 hours             vigilant_noether
b154d7c6856b   ixiacom/ixia-c-traffic-engine       "./entrypoint.sh"        42 hours ago   Up 42 hours             ecstatic_margulis
476f888283b7   ixiacom/ixia-c-traffic-engine       "./entrypoint.sh"        42 hours ago   Up 42 hours             adoring_roentgen

I have attached pcap file which seems to contain a valid POST request from client. 
[ixia-c-snappi-py-script-capture.zip](https://github.com/open-traffic-generator/ixia-c/files/7848209/ixia-c-snappi-py-script-capture.zip)

python3 -m pip freeze | grep requests
requests==2.18.4
requests-unixsocket==0.1.5

env/bin/python -m pip freeze | grep requests
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
requests==2.26.0

**Comment by ashutshkumr** [comment]
Upon searching the keywords from issue, it seems as if server is resetting connection. Could you please ensure that ixia-c-controller is responding to HTTP requests and that there are no other services running on port 80 ?

```sh
# send empty config
curl -kL -X POST https://localhost:80/config -d '{}'

# receive empty config
curl -kL https://localhost:80/config
```

**Comment by jvadalia** [comment]
Thanks, Script works with api location of https://localhost:80 but fails with api location of http://localhost:80. As per your suggestion curl based command worked fine with "https" but failed similarly with "http". I was using http rather than https to decode REST based commands between client and server.  Is there anyway to to force controller (server) to except non-encrypted RESTapi calls?

**Comment by ashutshkumr** [comment]
@jvadalia that's great news ! We'll certainly look into rejecting HTTP request against controller (thanks for reporting this).
