### ISSUE TITLE
Ability to use tools like Scapy to add headers for unsupported protocols.

### ISSUE THREAD

**Issue by UzairJawaid** [open-traffic-generator/ixia-c#69]
Can you provide documentation for this feature

**Comment by ANISH-GOTTAPU** [comment]
# **How to add headers for unsupported protocols.**

- Unsupported protocols can be added using custom packet header.
- A custom packet header is defined as a string of hex bytes.The string MUST contain sequence of valid hex bytes.Spaces or colons can be part of the bytes but will be discarded.


***Example of adding ARP header as custom header.***

```
import pytest
import snappi
from scapy.all import *


def test_scapy(api):
    pkt = ARP(hwtype=1, ptype=0x0800)
    config = api.config()  # type: snappi.config.Config
    (p1,) = config.ports.port(name="p1")
    (f1,) = config.flows.flow(name="p1")
    f1.tx_rx.port.tx_name = p1.name
    (custom,) = f1.packet.custom()
    custom.bytes = scapy.utils.repr_hex(pkt.__bytes__())
    print(config)


if __name__ == "__main__":
    pytest.main(["-s", __file__])

**Comment by ANISH-GOTTAPU** [comment]
Hi @UzairJawaid, closing this issue as information is provided. Please re-open the issue if you have any concern

**Comment by UzairJawaid** [comment]
Checked its working. Thank you
