### ISSUE TITLE
Login to Ixia container

### ISSUE THREAD

**Issue by anursharma** [open-traffic-generator/ixia-c#82]
I created Ixia container and accessing it with the command 

#docker exec  -it <container-id> bash

Is there any other way of logging in to the ixia container?

**Comment by ashutshkumr** [comment]
@anursharma are you referring to ixia-c-one or ixia-c ?

the only way to login to ixia-c containers is using docker exec (or kubectl exec in k8s env). In case you're using ixia-c-one,
- docker exec -it <ixia-c-one container> bash
- docker ps -a (list all child containers)
- docker exec -it <child container>
