### ISSUE TITLE
Ixia-c Container - Data Interfaces - eth1, eth2 ......

### ISSUE THREAD

**Issue by anursharma** [open-traffic-generator/ixia-c#84]
The interfaces created in Ixia container are "veth5aa8284, vetha3b8d37". How to figure out eth1 and eth2?

**Comment by ashutshkumr** [comment]
I'm assuming you're using ixia-c-one deployed as part of containerlab topology. If that's the case, the mapping between eth* and veth* can be seen from logs of ixia-c-one (docker logs "ixia-c-one container")
